/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Component;

/**
 *
 * @author LENOVO
 */
public class DialogAbsent extends javax.swing.JDialog {

    /**
     * Creates new form DialogAbsent
     */
    public DialogAbsent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        joLable1 = new Components.JoLable();
        joCheckBox1 = new Components.JoCheckBox();
        joCheckBox2 = new Components.JoCheckBox();
        joCheckBox3 = new Components.JoCheckBox();
        jPanel5 = new javax.swing.JPanel();
        joLable2 = new Components.JoLable();
        joCheckBox4 = new Components.JoCheckBox();
        joCheckBox5 = new Components.JoCheckBox();
        joCheckBox6 = new Components.JoCheckBox();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(102, 0, 204));

        joLable1.setText("joLable1");
        jPanel4.add(joLable1);

        joCheckBox1.setText("joCheckBox1");
        jPanel4.add(joCheckBox1);

        joCheckBox2.setText("joCheckBox2");
        jPanel4.add(joCheckBox2);

        joCheckBox3.setText("joCheckBox3");
        jPanel4.add(joCheckBox3);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 0, 255));

        joLable2.setText("joLable2");
        jPanel5.add(joLable2);

        joCheckBox4.setText("joCheckBox4");
        jPanel5.add(joCheckBox4);

        joCheckBox5.setText("joCheckBox5");
        jPanel5.add(joCheckBox5);

        joCheckBox6.setText("joCheckBox6");
        jPanel5.add(joCheckBox6);

        jPanel2.add(jPanel5);

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAbsent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAbsent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAbsent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAbsent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAbsent dialog = new DialogAbsent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private Components.JoCheckBox joCheckBox1;
    private Components.JoCheckBox joCheckBox2;
    private Components.JoCheckBox joCheckBox3;
    private Components.JoCheckBox joCheckBox4;
    private Components.JoCheckBox joCheckBox5;
    private Components.JoCheckBox joCheckBox6;
    private Components.JoLable joLable1;
    private Components.JoLable joLable2;
    // End of variables declaration//GEN-END:variables
}
