package Component;

import Components.JoTable;
import DAOSevervice.StudentService;
import Tools.JoAlert;

public class DialogChangeStudentNo extends javax.swing.JDialog {

    private int StudentID = 0;
    private JoTable table;

    public DialogChangeStudentNo(java.awt.Frame parent, boolean modal, int StudentID, String No, JoTable table) {
        super(parent, modal);
        this.StudentID = StudentID;
        this.table = table;
        initComponents();
        txtStudentNo.setText(No);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtStudentNo = new Components.JoTextField();
        btnSave = new Components.JoButtonIconfont();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txtStudentNo.setMinimumSize(new java.awt.Dimension(150, 40));
        txtStudentNo.setPlaceholder("ລະຫັດນັກຮຽນ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        getContentPane().add(txtStudentNo, gridBagConstraints);

        btnSave.setBackground(new java.awt.Color(0, 102, 102));
        btnSave.setText("ບັນທຶກ");
        btnSave.setJoIcons(jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons.SAVE);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        getContentPane().add(btnSave, gridBagConstraints);

        setSize(new java.awt.Dimension(322, 137));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtStudentNo.TextEmpty()) {
            StudentService service = new StudentService();
            if (!service.getChekStudentNo(txtStudentNo.getText())) {
                int issave = service.UpdateStudentNo(this.StudentID, txtStudentNo.getText());
                if (issave == 1) {
                    int row = table.getSelectedRow();
                    table.setValueAt(txtStudentNo.getText(), row, 2);
                    new JoAlert().messages("ແກ້ໄຂ", "ແກ້ໄຂລະຫັດສຳເລັດ", JoAlert.Icons.success);
                    this.dispose();
                } else {
                    new JoAlert().messages("ແກ້ໄຂ", "ແກ້ໄຂລະຫັດຜິດພາດ", JoAlert.Icons.warning);
                    this.dispose();
                }
            } else {
                new JoAlert().messages("ແກ້ໄຂ", "ລະຫັດນັກຮຽນ: " + txtStudentNo.getText() + " ຊຳກັນ ກະລຸນາໃຊ້ລະຫັດໃໝ່", JoAlert.Icons.warning);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.JoButtonIconfont btnSave;
    private Components.JoTextField txtStudentNo;
    // End of variables declaration//GEN-END:variables
}
