package Component;

import Chart.PieChartUI;
import Chart.PieChartUIModel;
import Components.JoLable;
import Model.ClassCountModel;
import Model.StudentCountModel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;

public class DialogStudentCount extends javax.swing.JDialog {

    public DialogStudentCount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void showTable(List<StudentCountModel> listcount) {
        tbData.JoClearModel();
        int count = 0;
        for (StudentCountModel item : listcount) {
            tbData.AddJoModel(new Object[]{tbData.autoNumber(), item.getClassRoom(), item.getCount()});
            count += item.getCount();
        }
        lblCount.setText("ຈຳນວນນັກຮຽນທັງໝົດ: " + count + " ຄົນ");
    }

    public void showChart(List<StudentCountModel> listcount) {
        PieChartUI pie = new PieChartUI();
        ClassCountModel Kindergarten = new ClassCountModel("ອານຸບານ", 0);
        ClassCountModel Elementary = new ClassCountModel("ປະຖົມ", 0);
        ClassCountModel JuniorHighSchool = new ClassCountModel("ມັດທະຍົມຕົ້ນ", 0);
        ClassCountModel HighSchool = new ClassCountModel("ມັດທະຍົມປາຍ", 0);
        for (StudentCountModel item : listcount) {
            if (item.getClassID() <= 20) {
                Kindergarten.setCount(Kindergarten.getCount() + item.getCount());
            } else if (item.getClassID() <= 25) {
                Elementary.setCount(Elementary.getCount() + item.getCount());
            } else if (item.getClassID() <= 29) {
                JuniorHighSchool.setCount(JuniorHighSchool.getCount() + item.getCount());
            } else {
                HighSchool.setCount(HighSchool.getCount() + item.getCount());
            }
        }
        pie.addData(new PieChartUIModel(Kindergarten.getName(), Kindergarten.getCount(), new Color(255, 82, 73)));
        pie.addData(new PieChartUIModel(Elementary.getName(), Elementary.getCount(), new Color(214, 187, 122)));
        pie.addData(new PieChartUIModel(JuniorHighSchool.getName(), JuniorHighSchool.getCount(), new Color(19, 208, 201)));
        pie.addData(new PieChartUIModel(HighSchool.getName(), HighSchool.getCount(), new Color(79, 128, 220)));
        pnChart.add(pie, BorderLayout.CENTER);
        //lable
        JoLable lblkin = new JoLable();
        JoLable lblele = new JoLable();
        JoLable lbljun = new JoLable();
        JoLable lblhig = new JoLable();
        lblkin.setText(Kindergarten.getName() + " " + Kindergarten.getCount() + " ຄົນ");
        lblkin.setForeground(new Color(255, 82, 73));
        lblele.setText(Elementary.getName() + " " + Elementary.getCount() + " ຄົນ");
        lblele.setForeground(new Color(214, 187, 122));
        lbljun.setText(JuniorHighSchool.getName() + " " + JuniorHighSchool.getCount() + " ຄົນ");
        lbljun.setForeground(new Color(19, 208, 201));
        lblhig.setText(HighSchool.getName() + " " + HighSchool.getCount() + " ຄົນ");
        lblhig.setForeground(new Color(79, 128, 220));
        pnFooter.add(lblkin);
        pnFooter.add(lblele);
        pnFooter.add(lbljun);
        pnFooter.add(lblhig);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        pnChart = new javax.swing.JPanel();
        pnFooter = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new Components.JoTable();
        jPanel3 = new javax.swing.JPanel();
        lblCount = new Components.JoLable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        pnChart.setLayout(new java.awt.BorderLayout());

        pnFooter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 5));
        pnChart.add(pnFooter, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel2.add(pnChart, gridBagConstraints);

        jPanel4.setLayout(new java.awt.BorderLayout());

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ຫ້ອງຮຽນ", "ຈຳນວນ"
            }
        ));
        jScrollPane1.setViewportView(tbData);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        lblCount.setText("ຈຳນວນນັກຮຽນທັງໝົດ:");
        lblCount.setFont(new java.awt.Font("Phetsarath OT", 1, 14)); // NOI18N
        jPanel3.add(lblCount);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel3, gridBagConstraints);

        setSize(new java.awt.Dimension(970, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private Components.JoLable lblCount;
    private javax.swing.JPanel pnChart;
    private javax.swing.JPanel pnFooter;
    private Components.JoTable tbData;
    // End of variables declaration//GEN-END:variables
}
