package Component;

import Components.JoTextField;
import DAOSevervice.ParentJobService;
import java.util.List;
import javax.swing.DefaultListModel;

public class DialogParentJob extends javax.swing.JDialog {

    private JoTextField textField;
    private ParentJobService service = new ParentJobService();

    public DialogParentJob(java.awt.Frame parent, boolean modal, JoTextField textField) {
        super(parent, modal);
        this.textField = textField;
        initComponents();
        List<String> items = service.getJobs();
        DefaultListModel model = new DefaultListModel();
        for (int index = 0; index < items.size(); index++) {
            String item = items.get(index);
            model.addElement(item);
        }
        jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(403, 276));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        System.out.println(jList1.getSelectedValue());
        textField.setText(jList1.getSelectedValue());
        this.dispose();
    }//GEN-LAST:event_jList1ValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
